[settings]
  # Stop on page processing errors?
  strict = true

  # Display progress?
  verbose = true

  # Display detailed debug output?
  debug = false

  # Where input files (pages and assets) are stored.
  site_dir = "site"

  # Where the output goes
  build_dir = "build"

  # Work as a website generator
  generator_mode = true

  # Files with other extensions are considered static assets
  # and copied to build/ unchanged.
  page_file_extensions = ["htm", "html", "md"]

  # Files with these extensions are ignored.
  ignore_extensions = ["draft"]

  # Treat files as content to insert in the template,
  # unless they have an <html> element in them.
  complete_page_selector = "html"

  # Use templates/base.html file for the page template.
  default_template_file = "templates/base.html"

  # The content will be inserted into its <div id="content"> element,
  # after its last already existing child.
  default_content_selector = "div#content"
  default_content_action = "append_child"

  # Set the document type to HTML5, unless the page already has
  # a doctype declaration.
  doctype = "<!DOCTYPE html>"
  keep_doctype = true

  # Indent HTML tags for readability
  pretty_print_html = true

  # Translate site/about.html to build/about/index.html
  # If set to false, then site/about.html will become build/about.html
  clean_urls = true

  # Look for plugin files in plugins/
  plugin_discovery = true
  plugin_dirs = ["plugins"]

[custom_options]
  # Atom feed metadata:
  site_url = "https://marijan.pro"

  site_author = "Marijan Petričević"
  site_author_email = "marijan.petricevic94@gmail.com"
  site_title = "marijan"
  site_icon = "https://marijan.pro/images/favicon.ico"

[preprocessors]
  md = 'pandoc -f commonmark+smart -t html'

[widgets.atom]
  widget = "atom"
  page = "posts/index.html"
  feed_file = "feed.atom"
  use_section = "posts"
  template = "templates/feed.atom"

[widgets.sitemap]
  widget = "sitemap"
  page = "posts/index.html"
  use_section = "posts"
  template = "templates/sitemap.xml"

[widgets.post-title]
  widget = "title"
  selector = [ "h1#post-title", "h1"]
  default = "marijan"
  append = " - marijan"

  # Insert a <title> element if a page doesn’t have one
  force = true

  # Keep the existing <title> if it exists and isn’t empty
  keep = false

[widgets.article-wrapper]
widget = "article-wrapper"
section = "posts"

[widgets.add-meta-description]
widget = "add-meta-description"

[index]
  index = true

  section = "posts"

  sort_descending = true
  sort_type = "calendar"
  sort_by = "date"

  date_formats = ["%F"] # YYYY-MM-DD

[index.fields]
  title = { selector = [ "h1#title", "h1" ] }
  author = { selector = [ "a[rel='author']" ] }
  excerpt = { selector = [ "p#excerpt"] }

[index.fields.date]
  selector = ["time#post-date", "time"]
  extract_attribute = "datetime"
  fallback_to_content = true

[index.views.posts-index]
  index_selector = "div#blog-posts"
  section = "posts"
  index_template = """
    <table class="table table-zebra">
      <thead>
        <tr>
          <th>Post Title</th>
          <th>Published</th>
        </tr>
      </thead>
      <tbody>
        {% for e in entries %}
        <tr>
          <td>
            <a class="link" href="{{e.url}}" title="{{e.title}}">{{e.title}}</a>
          </td>
          <td>
            {{e.date}}
          </td>
            {% if e.tags %}
            <div class="post-tags">
              <strong>Tags: </strong>
              {%- for t in e.tags -%}
                <a href="/posts/tag/{{t}}"><span class="post-tag">{{t}}</span></a>{% if not loop.last %}, {% endif %}
              {%- endfor -%}
            </div>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  """
